server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
spring:
  cloud:
    gateway:
      routes:
        - id: catalog
#          lb miatt lesz loadbalancer, nem beegetunk url-t, ami bejon loadbalancold
          uri: lb://catalog
#          predicates alapjan kell matchelni
          predicates:
          - Path=/catalog/**
          filters:
          - RewritePath=/catalog(?<segment>/?.*), /api$\{segment}
        - id: order
          uri: lb://order
          predicates:
          - Path=/order/**
          filters:
          - RewritePath=/order(?<segment>/?.*), /api$\{segment}
        - id: user-service
          uri: lb://user-service
          predicates:
          - Path=/user-service/**
          filters:
          - RewritePath=/user(?<segment>/?.*), /api$\{segment}