server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
hu:
  webuni:
    tokenlib:
      keypaths:
        public: /Users/zsoli/Gdf/Szakdolgozat/public.pem
        private: /Users/zsoli/Gdf/Szakdolgozat/private.pem
